package com.trcolgrove.daoentries;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.trcolgrove.daoentries.StoredSet;

import com.trcolgrove.daoentries.StoredSetDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig storedSetDaoConfig;

    private final StoredSetDao storedSetDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        storedSetDaoConfig = daoConfigMap.get(StoredSetDao.class).clone();
        storedSetDaoConfig.initIdentityScope(type);

        storedSetDao = new StoredSetDao(storedSetDaoConfig, this);

        registerDao(StoredSet.class, storedSetDao);
    }
    
    public void clear() {
        storedSetDaoConfig.getIdentityScope().clear();
    }

    public StoredSetDao getStoredSetDao() {
        return storedSetDao;
    }

}
