package com.trcolgrove.daoentries;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.trcolgrove.daoentries.ScoreSet;
import com.trcolgrove.daoentries.SurveyResponse;

import com.trcolgrove.daoentries.ScoreSetDao;
import com.trcolgrove.daoentries.SurveyResponseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig scoreSetDaoConfig;
    private final DaoConfig surveyResponseDaoConfig;

    private final ScoreSetDao scoreSetDao;
    private final SurveyResponseDao surveyResponseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        scoreSetDaoConfig = daoConfigMap.get(ScoreSetDao.class).clone();
        scoreSetDaoConfig.initIdentityScope(type);

        surveyResponseDaoConfig = daoConfigMap.get(SurveyResponseDao.class).clone();
        surveyResponseDaoConfig.initIdentityScope(type);

        scoreSetDao = new ScoreSetDao(scoreSetDaoConfig, this);
        surveyResponseDao = new SurveyResponseDao(surveyResponseDaoConfig, this);

        registerDao(ScoreSet.class, scoreSetDao);
        registerDao(SurveyResponse.class, surveyResponseDao);
    }
    
    public void clear() {
        scoreSetDaoConfig.getIdentityScope().clear();
        surveyResponseDaoConfig.getIdentityScope().clear();
    }

    public ScoreSetDao getScoreSetDao() {
        return scoreSetDao;
    }

    public SurveyResponseDao getSurveyResponseDao() {
        return surveyResponseDao;
    }

}
