package com.trcolgrove.daoentries;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STORED_SET".
 */
public class StoredSet {

    private Long id;
    private boolean uploaded;
    /** Not-null value. */
    private String scoreSetJson;

    public StoredSet() {
    }

    public StoredSet(Long id) {
        this.id = id;
    }

    public StoredSet(Long id, boolean uploaded, String scoreSetJson) {
        this.id = id;
        this.uploaded = uploaded;
        this.scoreSetJson = scoreSetJson;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public boolean getUploaded() {
        return uploaded;
    }

    public void setUploaded(boolean uploaded) {
        this.uploaded = uploaded;
    }

    /** Not-null value. */
    public String getScoreSetJson() {
        return scoreSetJson;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setScoreSetJson(String scoreSetJson) {
        this.scoreSetJson = scoreSetJson;
    }

}
