package com.trcolgrove.daoentries;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SURVEY_RESPONSE".
 */
public class SurveyResponse {

    private Long id;
    private String question;
    private Integer response;
    private java.util.Date date;

    public SurveyResponse() {
    }

    public SurveyResponse(Long id) {
        this.id = id;
    }

    public SurveyResponse(Long id, String question, Integer response, java.util.Date date) {
        this.id = id;
        this.question = question;
        this.response = response;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public Integer getResponse() {
        return response;
    }

    public void setResponse(Integer response) {
        this.response = response;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
